# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c880797ee36e8bf73cb428b0fa8e6233da2f0119fa6900641f55b87219446a923d82f43664114ccac9f5f76d298c8b32f30452c82a458bfc882dc76b3720d5

test:
  secret_key_base: 740e5474b6118aa1716ed0cd6fc0c69ec623603b1ad826c59fc4c40471bedd28a26b420eca9a3615d8ad61407483184838b503869bc86566297e34e1dbf125aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
